<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lyria.Infrastructure.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lyria.Infrastructure\Lyria.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Lyria.Application\Lyria.Application.csproj" />
    <ProjectReference Include="..\..\src\Lyria.Domain\Lyria.Domain.csproj" />
  </ItemGroup>

</Project>
