<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lyria.Application.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lyria.Application\Lyria.Application.csproj" />
    <ProjectReference Include="..\..\src\Lyria.Domain\Lyria.Domain.csproj" />
  </ItemGroup>

</Project>
