// <auto-generated />
using System;
using Lyria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lyria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LyriaDbContext))]
    [Migration("20260719015215_AddRestrictions")]
    partial class AddRestrictions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<string>("AddressComplement")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ComplementoDireccion");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pais");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstablecimientoId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Latitud");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Longitud");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Barrio");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Numero");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CodigoPostal");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("RatingPromedio");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Calle");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("TotalResenas");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Whatsapp");

                    b.HasKey("Id")
                        .HasName("PK_Sedes");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Sedes_Ciudad");

                    b.HasIndex("Province")
                        .HasDatabaseName("IX_Sedes_Provincia");

                    b.HasIndex("EstablishmentId", "IsActive")
                        .HasDatabaseName("IX_Sedes_EstablecimientoId_Activo");

                    b.HasIndex("EstablishmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Sedes_EstablecimientoId_Nombre");

                    b.ToTable("Sedes", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Categories.EstablishmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoriaEstablecimientoId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IconoUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_CategoriasEstablecimiento");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriasEstablecimiento_Codigo");

                    b.ToTable("CategoriasEstablecimiento", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstablecimientoId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoriaId");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("EmailContacto");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TelefonoContacto");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Instagram");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("Verificado");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("LogoUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(false)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("Slug");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVerificacion");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SitioWeb");

                    b.HasKey("Id")
                        .HasName("PK_Establecimientos");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Establecimientos_CategoriaId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Establecimientos_Activo");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_Establecimientos_Verificado");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Establecimientos_Slug");

                    b.ToTable("Establecimientos", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Restrictions.Restriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RestriccionId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_Restricciones");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Restricciones_Activo");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Restricciones_Nombre");

                    b.ToTable("Restricciones", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranch", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sedes_Establecimientos_EstablecimientoId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Establishment", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Categories.EstablishmentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Establecimientos_CategoriasEstablecimiento_CategoriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
