// <auto-generated />
using System;
using Lyria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lyria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LyriaDbContext))]
    [Migration("20260715044135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lyria.Domain.Establishments.Categories.EstablishmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoriaEstablecimientoId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.HasKey("Id")
                        .HasName("PK_CategoriasEstablecimiento");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriasEstablecimiento_Codigo");

                    b.ToTable("CategoriasEstablecimiento", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstablecimientoId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoriaId");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Instagram");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("Verificado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(false)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("Slug");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SitioWeb");

                    b.HasKey("Id")
                        .HasName("PK_Establecimientos");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Establecimientos_CategoriaId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Establecimientos_Activo");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_Establecimientos_Verificado");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Establecimientos_Slug");

                    b.ToTable("Establecimientos", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Establishment", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Categories.EstablishmentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Establecimientos_CategoriasEstablecimiento_CategoriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
