// <auto-generated />
using System;
using Lyria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lyria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LyriaDbContext))]
    partial class LyriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.BranchImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ImagenSedeId");

                    b.Property<string>("AlternativeText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TextoAlternativo");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacionUtc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NombreArchivo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("EsActivo");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("EsPrincipal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacionUtc");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Url");

                    b.HasKey("Id")
                        .HasName("PK_ImagenesSede");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_ImagenesSede_SedeId");

                    b.HasIndex("BranchId", "IsPrimary")
                        .HasDatabaseName("IX_ImagenesSede_SedeId_EsPrincipal");

                    b.HasIndex("BranchId", "IsActive", "SortOrder")
                        .HasDatabaseName("IX_ImagenesSede_SedeId_EsActivo_Orden");

                    b.ToTable("ImagenesSede", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.BranchSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HorarioSedeId");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time")
                        .HasColumnName("HoraCierre");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacionUtc");

                    b.Property<bool>("CrossesMidnight")
                        .HasColumnType("bit")
                        .HasColumnName("CruzaMedianoche");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint")
                        .HasColumnName("DiaSemana");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("EsActivo");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit")
                        .HasColumnName("Cerrado");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time")
                        .HasColumnName("HoraApertura");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacionUtc");

                    b.HasKey("Id")
                        .HasName("PK_HorariosSede");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_HorariosSede_SedeId");

                    b.HasIndex("BranchId", "DayOfWeek")
                        .HasDatabaseName("IX_HorariosSede_SedeId_DiaSemana");

                    b.HasIndex("BranchId", "DayOfWeek", "IsActive")
                        .HasDatabaseName("IX_HorariosSede_SedeId_DiaSemana_EsActivo");

                    b.ToTable("HorariosSede", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.BranchSpecialSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HorarioEspecialSedeId");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time")
                        .HasColumnName("HoraCierre");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacionUtc");

                    b.Property<bool>("CrossesMidnight")
                        .HasColumnType("bit")
                        .HasColumnName("CruzaMedianoche");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Fecha");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("EsActivo");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit")
                        .HasColumnName("Cerrado");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time")
                        .HasColumnName("HoraApertura");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Motivo");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacionUtc");

                    b.HasKey("Id")
                        .HasName("PK_HorariosEspecialesSede");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_HorariosEspecialesSede_SedeId");

                    b.HasIndex("BranchId", "Date")
                        .HasDatabaseName("IX_HorariosEspecialesSede_SedeId_Fecha");

                    b.HasIndex("BranchId", "Date", "IsActive")
                        .HasDatabaseName("IX_HorariosEspecialesSede_SedeId_Fecha_EsActivo");

                    b.ToTable("HorariosEspecialesSede", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<string>("AddressComplement")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ComplementoDireccion");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pais");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstablecimientoId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Latitud");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Longitud");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Barrio");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Numero");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CodigoPostal");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("RatingPromedio");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Calle");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ZonaHoraria");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("TotalResenas");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Whatsapp");

                    b.HasKey("Id")
                        .HasName("PK_Sedes");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Sedes_Ciudad");

                    b.HasIndex("Province")
                        .HasDatabaseName("IX_Sedes_Provincia");

                    b.HasIndex("EstablishmentId", "IsActive")
                        .HasDatabaseName("IX_Sedes_EstablecimientoId_Activo");

                    b.HasIndex("EstablishmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Sedes_EstablecimientoId_Nombre");

                    b.ToTable("Sedes", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranchRestriction", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<Guid>("RestrictionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RestriccionId");

                    b.Property<byte>("ComplianceLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("NivelCumplimiento");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("bit")
                        .HasColumnName("Certificado");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Observacion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("BranchId", "RestrictionId")
                        .HasName("PK_SedesRestricciones");

                    b.HasIndex("RestrictionId")
                        .HasDatabaseName("IX_SedesRestricciones_RestriccionId");

                    b.HasIndex("BranchId", "ComplianceLevel")
                        .HasDatabaseName("IX_SedesRestricciones_SedeId_NivelCumplimiento");

                    b.HasIndex("BranchId", "IsActive")
                        .HasDatabaseName("IX_SedesRestricciones_SedeId_Activo");

                    b.HasIndex("RestrictionId", "IsActive")
                        .HasDatabaseName("IX_SedesRestricciones_RestriccionId_Activo");

                    b.ToTable("SedesRestricciones", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranchService", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ServicioId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("Disponible");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Observacion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("BranchId", "ServiceId")
                        .HasName("PK_SedesServicios");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_SedesServicios_ServicioId");

                    b.HasIndex("BranchId", "IsActive")
                        .HasDatabaseName("IX_SedesServicios_SedeId_Activo");

                    b.HasIndex("ServiceId", "IsActive")
                        .HasDatabaseName("IX_SedesServicios_ServicioId_Activo");

                    b.ToTable("SedesServicios", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Categories.EstablishmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoriaEstablecimientoId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IconoUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_CategoriasEstablecimiento");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriasEstablecimiento_Nombre");

                    b.ToTable("CategoriasEstablecimiento", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstablecimientoId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoriaId");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("EmailContacto");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TelefonoContacto");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Instagram");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("Verificado");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("LogoUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(false)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("Slug");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVerificacion");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SitioWeb");

                    b.HasKey("Id")
                        .HasName("PK_Establecimientos");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Establecimientos_CategoriaId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Establecimientos_Activo");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_Establecimientos_Verificado");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Establecimientos_Slug");

                    b.ToTable("Establecimientos", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Restrictions.Restriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RestriccionId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_Restricciones");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Restricciones_Activo");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Restricciones_Nombre");

                    b.ToTable("Restricciones", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RolId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Services.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ServicioId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IconoUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_Servicios");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Servicios_Activo");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Servicios_Nombre");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Users.RefreshTokens.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefreshTokenId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaExpiracion");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRevocacion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("TokenHash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id")
                        .HasName("PK_UsuarioRefreshTokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UsuarioRefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UsuarioRefreshTokens_UsuarioId");

                    b.ToTable("UsuarioRefreshTokens", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("FechaNacimiento");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("EmailVerificado");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimaConexion");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("HashContrasena");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FotoUrl");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id")
                        .HasName("PK_Usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuarios_Email");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Users.UserRestrictions.UserRestriction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.Property<Guid>("RestrictionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RestriccionId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("ImportanceLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NivelImportancia");

                    b.HasKey("UserId", "RestrictionId")
                        .HasName("PK_UsuarioRestricciones");

                    b.HasIndex("RestrictionId");

                    b.ToTable("UsuarioRestricciones", "dbo");
                });

            modelBuilder.Entity("Lyria.Domain.Users.UserRoles.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioRolId");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAsignacion");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SedeId");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFinalizacion");

                    b.Property<Guid?>("EstablishmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstablecimientoId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RolId");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("AlcanceTipo");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id")
                        .HasName("PK_UsuarioRoles");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_UsuarioRoles_SedeId")
                        .HasFilter("[SedeId] IS NOT NULL");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("IX_UsuarioRoles_EstablecimientoId")
                        .HasFilter("[EstablecimientoId] IS NOT NULL");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UsuarioRoles_RolId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UsuarioRoles_UsuarioId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.BranchImage", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Branches.EstablishmentBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ImagenesSede_Sedes_SedeId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.BranchSchedule", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Branches.EstablishmentBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HorariosSede_Sedes_SedeId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.BranchSpecialSchedule", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Branches.EstablishmentBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HorariosEspecialesSede_Sedes_SedeId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranch", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sedes_Establecimientos_EstablecimientoId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranchRestriction", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Branches.EstablishmentBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SedesRestricciones_Sedes_SedeId");

                    b.HasOne("Lyria.Domain.Restrictions.Restriction", null)
                        .WithMany()
                        .HasForeignKey("RestrictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SedesRestricciones_Restricciones_RestriccionId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Branches.EstablishmentBranchService", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Branches.EstablishmentBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SedesServicios_Sedes_SedeId");

                    b.HasOne("Lyria.Domain.Services.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SedesServicios_Servicios_ServicioId");
                });

            modelBuilder.Entity("Lyria.Domain.Establishments.Establishment", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Categories.EstablishmentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Establecimientos_CategoriasEstablecimiento_CategoriaId");
                });

            modelBuilder.Entity("Lyria.Domain.Users.RefreshTokens.UserRefreshToken", b =>
                {
                    b.HasOne("Lyria.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRefreshTokens_Usuarios_UsuarioId");
                });

            modelBuilder.Entity("Lyria.Domain.Users.UserRestrictions.UserRestriction", b =>
                {
                    b.HasOne("Lyria.Domain.Restrictions.Restriction", null)
                        .WithMany()
                        .HasForeignKey("RestrictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRestricciones_Restricciones_RestriccionId");

                    b.HasOne("Lyria.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRestricciones_Usuarios_UsuarioId");
                });

            modelBuilder.Entity("Lyria.Domain.Users.UserRoles.UserRole", b =>
                {
                    b.HasOne("Lyria.Domain.Establishments.Branches.EstablishmentBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UsuarioRoles_Sedes_SedeId");

                    b.HasOne("Lyria.Domain.Establishments.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UsuarioRoles_Establecimientos_EstablecimientoId");

                    b.HasOne("Lyria.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRoles_Roles_RolId");

                    b.HasOne("Lyria.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRoles_Usuarios_UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
