<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lyria.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="TngTech.ArchUnitNET" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lyria.Domain\Lyria.Domain.csproj" />
    <ProjectReference Include="..\..\src\Lyria.Application\Lyria.Application.csproj" />
    <ProjectReference Include="..\..\src\Lyria.Infrastructure\Lyria.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Lyria.Api\Lyria.Api.csproj" />
  </ItemGroup>

</Project>
